### ISSUE TITLE
Restructure contents of repo

### ISSUE THREAD

**Issue by ravimashru** [instituteofai/ML-101#1]
@kumarchandan @divyanshbajpai should we modify this repository so that its structure matches exactly what we have on Canvas LMS?

We can then add all the material, assignments and quizzes (without answers) posted there into this repo for use with future batches.

What do you guys think?

**Comment by kumarchandan** [comment]
@mashruravi Sounds great! We should make the structure of Canvas and Github similar.

One question about the new batch, If they already know the content of the future sessions. Wouldn't it be a problem? No element of surprise for them.

What do you think?

**Comment by ravimashru** [comment]
I would prefer to have an "open content" approach instead of surprises. We would just go in more depth for explanations during contact sessions. 

This will also allow the above average students in a batch go as far as they can without getting bored.

**Comment by kumarchandan** [comment]
Okay. Let's do it.
@mashruravi  +1 for "open content".

**Comment by ravimashru** [comment]
I've added this to our "To Do" lane. Let us do this once we finish the current batch. If we restructure now then some of the links students might have bookmarked will not work anymore.
